#docker-image.yml
name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'trigger source'
        required: false
        default: 'cron-job.org'
jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Refresh cache
        run: |
          set -e
          git config user.name "kijin9riandis03"
          git config user.email "kijin9riandis03@collaborative.li"
          if [ ! -f data-commit.txt ]; then
            curl -o data-commit.txt https://raw.githubusercontent.com/menju2ikg8uti/rem/main/data-commit.txt
            echo "[Token](https://github.com/settings/tokens)" >> README.md
            git add data-commit.txt README.md
            RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
            git commit -m "$RANDOM_LINE"
            git push
          fi
          mkdir -p logs
          ACCOUNT_ID="$(basename "$GITHUB_REPOSITORY")"
          FILE="logs/${ACCOUNT_ID}.txt"
          printf "name = 'monitoring'\nmain = 'worker.js'\ncompatibility_date = '%s'\nworkers_dev = true\n"  "$(date +%F)" > wrangler.toml
          echo 'export default{async fetch(){return new Response("monitoring",{headers:{"content-type":"text/plain"}})}}' > worker.js
          echo "$(date '+%T') | flag=$(shuf -i100000-999999 -n1)" >> "$FILE"
          git add "$FILE" worker.js wrangler.toml
          RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
          git commit -m "$RANDOM_LINE"
          git push
          sleep $(( ( $(date +%s) % 3 ) + 1 ))
          echo "$(date '+%T') | profile3=$(shuf -i1000-9999 -n1)" >> "$FILE"
          git add "$FILE"
          RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
          git commit -m "$RANDOM_LINE"
          git push
          sleep $(( ( $(date +%s) % 3 ) + 1 ))
          NASHJ="$(sha256sum "$FILE" | awk '{print $1}')"
          echo "$(date '+%T') | tree_hash=$NASHJ" >> "$FILE"
          git add "$FILE"
          RANDOM_LINE="$(shuf -n 1 data-commit.txt | tr -d '\r')"
          git commit -m "$RANDOM_LINE"
          git push
